"""WAF / IP-block / rate-limit signature detection.

The goal is to distinguish a *plain* 403 (a genuinely forbidden path, which is a
useful recon signal) from a 403/503/429 produced by a WAF or an IP block, which
means "rotate egress (proxy / WARP) and retry".
"""
from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass
class WafVerdict:
    blocked: bool = False
    vendor: str = ""
    reason: str = ""
    ratelimited: bool = False


# vendor -> (header substrings, body substrings/regex)
_SIGNATURES: list[tuple[str, list[str], list[str]]] = [
    ("cloudflare",
     ["cf-ray", "cf-chl", "cf-mitigated", "server: cloudflare", "__cf_bm"],
     ["attention required! | cloudflare", "sorry, you have been blocked",
      "cloudflare ray id", "/cdn-cgi/challenge-platform", "error 1020",
      "checking if the site connection is secure", "ray id:"]),
    ("akamai",
     ["akamaighost", "x-akamai", "akamai-grn", "ak_bmsc", "x-akamai-transformed"],
     ["access denied", "you don't have permission to access",
      "reference&#32;#18", "reference #18.", "errors.edgesuite.net",
      "akamai error"]),
    ("aws-waf",
     ["x-amzn-requestid", "x-amzn-errortype", "awselb", "x-amz-cf-id"],
     ["request blocked", "aws waf", "<title>403 forbidden</title>"]),
    ("imperva-incapsula",
     ["x-iinfo", "incap_ses", "visid_incap", "x-cdn: incapsula"],
     ["incapsula incident id", "_incapsula_resource", "powered by incapsula",
      "subject to imperva"]),
    ("sucuri",
     ["x-sucuri-id", "x-sucuri-cache", "server: sucuri/cloudproxy"],
     ["access denied - sucuri website firewall", "sucuri website firewall",
      "cloudproxy"]),
    ("f5-bigip",
     ["x-waf-event", "bigipserver", "ts01", "x-cnection"],
     ["the requested url was rejected", "please consult with your administrator",
      "support id is"]),
    ("fastly",
     ["x-served-by: cache", "x-fastly", "via: 1.1 varnish"],
     ["fastly error", "request could not be processed"]),
    ("wordfence",
     [],
     ["generated by wordfence", "your access to this site has been limited"]),
    ("datadome",
     ["x-datadome", "datadome="],
     ["captcha-delivery.com", "geo.captcha-delivery"]),
    ("perimeterx",
     ["x-px", "_px2", "_px3"],
     ["px-captcha", "perimeterx", "please verify you are a human"]),
]

# Wayback / Archive.org specific throttling signals
_ARCHIVE_BLOCK = [
    "too many requests", "your ip has been blocked", "rate exceeded",
    "slow down", "you have been blocked", "503 service",
    "the wayback machine has not archived that url", "no captures",
]


def detect(status_code: int, headers: dict[str, str] | None, body: str | None) -> WafVerdict:
    headers = headers or {}
    hblob = " ".join(f"{k}: {v}" for k, v in headers.items()).lower()
    bblob = (body or "")[:20000].lower()

    # explicit rate limiting
    if status_code == 429:
        return WafVerdict(True, "rate-limit", "HTTP 429 Too Many Requests", True)

    # vendor signatures (most reliable)
    for vendor, hsigs, bsigs in _SIGNATURES:
        if any(s in hblob for s in hsigs) or any(s in bblob for s in bsigs):
            # only treat as a *block* if the status indicates one, or a
            # challenge/blocked phrase is present in the body
            blocked = status_code in (401, 403, 406, 429, 503) or any(
                p in bblob for p in ("blocked", "denied", "rejected", "captcha",
                                     "challenge", "limited", "ray id"))
            if blocked:
                return WafVerdict(True, vendor, f"{vendor} signature ({status_code})",
                                  status_code in (429, 503))

    # archive.org throttle
    if any(s in bblob for s in _ARCHIVE_BLOCK):
        return WafVerdict(True, "archive.org", "archive.org throttle/block",
                          status_code in (429, 503))

    # generic server-side throttle / unavailable
    if status_code == 503:
        return WafVerdict(True, "generic", "HTTP 503 Service Unavailable", True)

    # blank/short 403 with a 'forbidden' shell is often an edge block
    if status_code == 403 and ("forbidden" in bblob and len(bblob) < 600):
        return WafVerdict(True, "generic", "HTTP 403 edge block", False)

    return WafVerdict(False, "", "", False)


def is_block_status(status_code: int) -> bool:
    return status_code in (403, 406, 429, 503)
